let envSource = Bun.env;
const {
  PORT,
  PGHOST,
  PGUSER,
  PGPASSWORD,
  PGPORT,
  PGDATABASE,
  APP_INS_CONNECTION,
  // AAD_CLIENT_ID,
  // AAD_SCP,
  // AAD_SP_AUTHORITY,
  // AAD_SP_TENANT_ID,
  // AAD_SP_CLIENT_ID,
  // AAD_SP_CLIENT_SECRET,
  // AAD_SP_CLIENT_SCOPE,
  // MONGO_DB_NAME,
  // MONGO_DB_PASS,
  // MONGO_DB_USER,
  // MONGO_DB_HOST,
  API_ENDPOINT,
  DATABASE_URL,
} = envSource;

export default {
  Port: PORT,
  PgHost: PGHOST,
  PgUser: PGUSER,
  PgPassword: PGPASSWORD,
  PgPort: PGPORT,
  PgDatabase: PGDATABASE,
  AppInsConnection: APP_INS_CONNECTION,
  // AdClientId: AAD_CLIENT_ID,
  // AdScope: AAD_SCP,
  // Authority: AAD_SP_AUTHORITY,
  // TenantId: AAD_SP_TENANT_ID,
  // ClientId: AAD_SP_CLIENT_ID,
  // ClientSecret: AAD_SP_CLIENT_SECRET,
  // ClientScope: AAD_SP_CLIENT_SCOPE,
  // MongoDBName: MONGO_DB_NAME,
  // MongoDBPass: MONGO_DB_PASS,
  // MongoDBUser: MONGO_DB_USER,
  // MongoDBHost: MONGO_DB_HOST,
  ApiEndpoint: API_ENDPOINT,
  DatabaseUrl: DATABASE_URL,
};
